
version: 2

models:
  - name: audience_master
    description: "A starter dbt model"
    columns:
      - name: crn
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
