bigquery:
  outputs:
    dev:
      dataset: shubham
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: gcp-wow-rwds-ai-mmm-dev
      threads: 1
      type: bigquery
  target: dev