bigquery:
  outputs:
    dev:
      dataset: shubham_dbt_demo
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: us-central1
      method: oauth
      priority: interactive
      project: digital-aloe-455622-i6
      threads: 1
      type: bigquery
  target: dev